operations:
   BatchAssociateScramSecret:
    resource_name: ScramSecretAssociation
    operation_type: Create
#   ListScramSecrets:
#    resource_name: ScramSecretAssociation
#    operation_type:
#    - ReadOne
#    - Get
#   BatchDisassociateScramSecret:
#    resource_name: ScramSecretAssociation
#    operation_type: Delete
ignore:
  field_paths:
    - CreateClusterInput.BrokerNodeGroupInfo
    - CreateClusterInput.ClusterName
    - CreateClusterInput.ConfigurationInfo
    - CreateConfigurationInput.Name
    - CreateConfigurationInput.ServerProperties
    - BatchAssociateScramSecretInput.ClusterArn
    - BatchAssociateScramSecretInput.SecretArnList
    - BatchAssociateScramSecretOutput.UnprocessedScramSecrets
resources:
  Configuration:
    exceptions:
      errors:
        404:
          code: BadRequestException
  Cluster:
    exceptions:
      errors:
        404:
          code: BadRequestException
