/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ScramSecretAssociationParameters defines the desired state of ScramSecretAssociation
type ScramSecretAssociationParameters struct {
	// Region is which region the ScramSecretAssociation will be created.
	// +kubebuilder:validation:Required
	Region                                 string `json:"region"`
	CustomScramSecretAssociationParameters `json:",inline"`
}

// ScramSecretAssociationSpec defines the desired state of ScramSecretAssociation
type ScramSecretAssociationSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       ScramSecretAssociationParameters `json:"forProvider"`
}

// ScramSecretAssociationObservation defines the observed state of ScramSecretAssociation
type ScramSecretAssociationObservation struct {
	// The Amazon Resource Name (ARN) of the cluster.
	ClusterARN *string `json:"clusterARN,omitempty"`
}

// ScramSecretAssociationStatus defines the observed state of ScramSecretAssociation.
type ScramSecretAssociationStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ScramSecretAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ScramSecretAssociation is the Schema for the ScramSecretAssociations API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type ScramSecretAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ScramSecretAssociationSpec   `json:"spec"`
	Status            ScramSecretAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScramSecretAssociationList contains a list of ScramSecretAssociations
type ScramSecretAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScramSecretAssociation `json:"items"`
}

// Repository type metadata.
var (
	ScramSecretAssociationKind             = "ScramSecretAssociation"
	ScramSecretAssociationGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScramSecretAssociationKind}.String()
	ScramSecretAssociationKindAPIVersion   = ScramSecretAssociationKind + "." + GroupVersion.String()
	ScramSecretAssociationGroupVersionKind = GroupVersion.WithKind(ScramSecretAssociationKind)
)

func init() {
	SchemeBuilder.Register(&ScramSecretAssociation{}, &ScramSecretAssociationList{})
}
